version: '2'
services:
  java-maven-tomcat:
    # 免构建镜像，未修改构建文件下等同于构建本地镜像，如使用本地 build 需注释此行并关闭 build 注释。
    image: registry.cn-hangzhou.aliyuncs.com/springjk/java-maven-tomcat
    # 构建本地镜像
    # build: ./java-maven-tomcat
    links:
      - mysql
    # 将容器的8080端口绑定到宿主机的80端口
    ports:
      - "80:8080"
    # java-maven-tomcat 容器启动后的运行命令
    command: "bash /tmp/build.sh"
    volumes:
      # 挂载 Maven 的缓存目录
      - ./data/maven:/usr/share/maven/ref/repository
      # 挂载 JAVA 源代码目录
      - ./code:/tmp/code
    restart: always
  mysql:
    image: mysql:5.7
    container_name: codingirls
    ports:
      - 3306:3306
    environment:
      - LANG=C.UTF-8
      - TERM=dumb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codingirls
      - MYSQL_PASSWORD=12345678
      - MYSQL_USER=codingirls
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tmpfs:
      - /var/lib/mysql/:rw,noexec,nosuid,size=600m
      - /tmp/:rw,noexec,nosuid,size=50m
    networks:
      main:
        aliases:
          - codingirls
networks:
  main: